# Generated by Django 5.2.8 on 2026-04-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('ar_model', models.FileField(blank=True, help_text='Upload 3D model for AR view', null=True, upload_to='product_ar/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
