# Generated by Django 5.2.8 on 2026-06-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Mejlis', max_length=50),
        ),
    ]
