# Generated by Django 5.2.8 on 2026-04-28 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ar_model',
            field=models.FileField(blank=True, help_text='Upload a .glb file for the best 3D/AR web experience.', null=True, upload_to='product_ar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf', 'usdz'])]),
        ),
    ]
