# Generated by Django 5.2.8 on 2026-05-02 09:04

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_ar_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ar_model',
            field=models.FileField(blank=True, help_text='Upload a .glb file for the best 3D/AR web experience.', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='product_ar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf', 'usdz'])]),
        ),
    ]
