# Generated by Django 5.2.8 on 2026-05-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_ar_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Sofa', 'Sofa'), ('Mejlis', 'Mejlis'), ('Table', 'Table'), ('Bed', 'Bed'), ('Cabinet', 'Cabinet'), ('Side Drawer', 'Side Drawer')], default='Sofa', max_length=50),
        ),
    ]
